server:
  port: 8091
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: schedulerdb
      #user: scheduleruser
      #password: secret

app:
  providers:
    - one.microproject.scheduler.exampletask.JobProviderImpl
  iam-client:
    organization-id: backend-services
    project-id: scheduler
    base-url: http://127.0.0.1:8080
    polling-interval: 30
    time-unit: SECONDS

logging:
  level:
    root: INFO
    one:
      microproject:
        iamservice:
          client:
            impl: INFO
