server:
  port: 8090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loggerdb
      #user: loggeruser
      #password: secret
      #uri: mongo://localhost:27017/test
