server:
  port: 8090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loggerdb
      user: logger-user
      password: secret
      #uri: mongo://localhost:27017/test
